alter table public.profiles
add column if not exists has_premium_access boolean default false;

alter table public.profiles
add column if not exists premium_plan text;

alter table public.profiles
add column if not exists stripe_customer_id text;

alter table public.profiles
add column if not exists premium_updated_at timestamp with time zone;

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_key text not null,
  status text not null default 'inactive',
  stripe_customer_id text,
  stripe_subscription_id text unique,
  checkout_session_id text,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists subscriptions_user_id_idx
on public.subscriptions (user_id);

create index if not exists subscriptions_status_idx
on public.subscriptions (status);

alter table public.subscriptions enable row level security;

drop policy if exists "Users can view own subscriptions" on public.subscriptions;
create policy "Users can view own subscriptions"
on public.subscriptions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Service role manages subscriptions" on public.subscriptions;
create policy "Service role manages subscriptions"
on public.subscriptions
for all
to service_role
using (true)
with check (true);
