create table if not exists public.workout_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  program_id text not null,
  workout_id text not null,
  completed_at timestamp with time zone,
  last_opened_at timestamp with time zone,
  updated_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  unique (user_id, workout_id)
);

create index if not exists workout_progress_user_id_idx
on public.workout_progress (user_id);

create index if not exists workout_progress_program_id_idx
on public.workout_progress (program_id);

alter table public.workout_progress enable row level security;

drop policy if exists "Users can view own workout progress" on public.workout_progress;
create policy "Users can view own workout progress"
on public.workout_progress
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own workout progress" on public.workout_progress;
create policy "Users can insert own workout progress"
on public.workout_progress
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own workout progress" on public.workout_progress;
create policy "Users can update own workout progress"
on public.workout_progress
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
